### ISSUE TITLE
add rust support.

### ISSUE THREAD

**Issue by LollipopFt** [ONLYOFFICE/plugin-highlightcode#32]
Yeah... would be cool if you could. I'm ok if you can't.

**Comment by ShockwaveNN** [comment]
@LollipopFt Hi, thanks for contacting us

I've added issue 51375 in our private issue tracker to discuss this with our team

**Comment by ShockwaveNN** [comment]
We added `rust` support via updating third party library
https://github.com/ONLYOFFICE/plugin-highlightcode/commit/9166d1575c6236e39a07d0cc0326e86823f56c5d

Currently it's on develop, you can try it, but can contain any number on unfixed bugs

**Comment by LollipopFt** [comment]
thank you!

**Comment by ShockwaveNN** [comment]
I'll leave this issue opened until we merge `develop` to `master`

**Comment by trofim24** [comment]
Fixed
We've released v.1.0.0
