### ISSUE TITLE
Why don't you publish `.plugin` file?

### ISSUE THREAD

**Issue by bphd** [ONLYOFFICE/plugin-highlightcode#37]

**Comment by ShockwaveNN** [comment]
Hi, I agree with you, we should do that

I've created issue 55378 in our private issue tracker to discuss this

P.S. Are you really think that creating 16!!! similar issue in each repo is really required?
https://github.com/ONLYOFFICE/plugin-highlightcode/issues/37
https://github.com/ONLYOFFICE/plugin-grammalecte/issues/4
https://github.com/ONLYOFFICE/plugin-easybib/issues/10
https://github.com/ONLYOFFICE/plugin-deepl/issues/5
https://github.com/ONLYOFFICE/plugin-autocomplete/issues/28
https://github.com/ONLYOFFICE/plugin-apertium/issues/4
https://github.com/ONLYOFFICE/plugin-youtube/issues/37
https://github.com/ONLYOFFICE/plugin-wordscounter/issues/9
https://github.com/ONLYOFFICE/plugin-wordpress/issues/6
https://github.com/ONLYOFFICE/plugin-thesaurus/issues/34
https://github.com/ONLYOFFICE/plugin-speech/issues/50
https://github.com/ONLYOFFICE/plugin-rainbow/issues/3
https://github.com/ONLYOFFICE/plugin-photoeditor/issues/36
https://github.com/ONLYOFFICE/plugin-ocr/issues/29
https://github.com/ONLYOFFICE/plugin-languagetool/issues/17
https://github.com/ONLYOFFICE/plugin-html/issues/5
I'm sorry but this looks just a waste of my time, one issue to discuss it should be enough

**Comment by bphd** [comment]
Sorry, I didn't considered that those repo were related by any means. So I guessed that it should be useful to ask everywhere

**Comment by ShockwaveNN** [comment]
Those repos are located in same organization, so they maintained by the same people

So if we add those feature in one we can add it almost instantly to all others

**Comment by bphd** [comment]
Considering that this organization is so hearing and conciliating with their people, I permit myself to suggest to add the OnlyOffice plug-ins store inside the OO client itself. Because it's utterly unfriendly to users to take them to "Plug-ins settings > OnlyOffice wiki > OnlyOffice plug-ins store > GitHub repos > Compilation > Plug-in file importation". I don't see the friend that use OO as a daily driver after my advice succeed getting an add-on following this process. And by the way, this integrated store should be plug and play, like an App Store, Play Store, Flathub Store, any stores. Not with wiki/repos/compilations/import things

**Comment by ShockwaveNN** [comment]
Yes we agree with you and currently, we have a plugin store in the works

Can't promise any estimates, since it's rather hard to make a plugin store right

**Comment by trofim24** [comment]
[Fixed](https://github.com/ONLYOFFICE/plugin-highlightcode/releases/tag/v1.0.0)
